const SET_LOGGED_IN = 'SET_LOGGED_IN';

const SET_LOADING = 'SET_LOADING';
const SET_ERROR = 'SET_ERROR';
const SET_USER = 'SET_USER';

const SET_SUCCESS = 'SET_SUCCESS';

// ORDERS
const SET_ORDERS = 'SET_ORDERS';
const SET_ORDER_COUNT = 'SET_ORDER_COUNT';
const SET_TOTAL_SALES = 'SET_TOTAL_SALES';
const SET_TOTAL_CREDITS = 'TOTAL_CREDITS';
const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER';
const LOADING_ORDERS = 'LOADING_ORDERS';
const SET_SELECTED_CREDIT = 'SET_SELECTED_CREDIT';
const SET_LOANS = 'SET_LOANS';
const SET_PAYMENTS = 'SET_PAYMENTS';

// Order Filtering
const SET_SELECTED_ORDER_STATUS = 'SET_SELECTED_ORDER_STATUS';
const SET_SELECTED_ORDER_PAYMENT_METHOD = 'SET_SELECTED_ORDER_PAYMENT_METHOD';
const SET_SELECTED_ORDER_PAYMENT_STATUS = 'SET_SELECTED_ORDER_PAYMENT_STATUS';
const SET_ORDERS_FILTERED = 'SET_ORDERS_FILTERED';
const SET_CREDITS = 'SET_CREDITS';

// PRODUCTS
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_PRODUCT_COUNT = 'SET_PRODUCT_COUNT';
const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

// USERS
const SET_USERS = 'SET_USERS';
const SET_USER_COUNT = 'SET_USER_COUNT';
const SET_USER_DETAILS = 'SET_USER_DETAILS';

const SET_DISTRIBUTORS = 'SET_DISTRIBUTORS';

// LOGS
const SET_SUCCESS_LOGS = 'SET_SUCCESS_LOGS';
const LOADING_LOGS = 'LOADING_LOGS';

// PROJECTS
const SET_PROJECTS = 'SET_PROJECTS';
const SAVE_NEW_PROJECT = 'SAVE_NEW_PROJECT';
const PROJECT_ERROR = 'PROJECT_ERROR';
const LOADING_PROJECT = 'LOADING_PROJECT';

export {
  SET_LOGGED_IN,
  SET_ORDERS,
  SET_LOADING,
  SET_ERROR,
  SET_USER,
  SET_SUCCESS,
  SET_ORDER_COUNT,
  SET_PRODUCTS,
  SET_PRODUCT_COUNT,
  SET_USERS,
  SET_USER_COUNT,
  SET_TOTAL_SALES,
  SET_SELECTED_ORDER,
  LOADING_PRODUCTS,
  LOADING_ORDERS,
  SET_SELECTED_CREDIT,
  SET_TOTAL_CREDITS,
  SET_USER_DETAILS,
  SET_DISTRIBUTORS,
  SET_SELECTED_ORDER_STATUS,
  SET_SELECTED_ORDER_PAYMENT_METHOD,
  SET_SELECTED_ORDER_PAYMENT_STATUS,
  SET_ORDERS_FILTERED,
  SET_LOANS,
  SET_PAYMENTS,
  SET_CREDITS,
  SET_SUCCESS_LOGS,
  LOADING_LOGS,
  SET_PROJECTS,
  SAVE_NEW_PROJECT,
  PROJECT_ERROR,
  LOADING_PROJECT,
};
